name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Server Dependencies
        working-directory: ./server
        run: npm install

      - name: Install Client Dependencies
        working-directory: ./client
        run: npm install

      - name: Build Next.js Client
        working-directory: ./client
        run: npm run build

  deploy:
    needs: build-and-test # Wait for the build to pass first!
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd maintenance-tracker-repo
            git pull origin main
            docker-compose down
            docker-compose up -d --build
